"""FR-15: Add common code management

Revision ID: b9e54cc56a05
Revises: a1f3c2d4e5f6
Create Date: 2025-12-08 22:57:03.676730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9e54cc56a05'
down_revision: Union[str, Sequence[str], None] = 'a1f3c2d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('common_code_groups',
    sa.Column('group_code', sa.String(length=100), nullable=False, comment='그룹 고유 코드 (예: BUSINESS_TYPE, ERROR_CODE)'),
    sa.Column('group_name', sa.String(length=200), nullable=False, comment='그룹 이름 (예: 업무 구분, 에러코드)'),
    sa.Column('description', sa.Text(), nullable=True, comment='그룹 설명'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='활성화 여부'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_common_code_groups_group_code'), 'common_code_groups', ['group_code'], unique=True)
    op.create_index(op.f('ix_common_code_groups_is_active'), 'common_code_groups', ['is_active'], unique=False)
    op.create_table('common_code_items',
    sa.Column('group_id', sa.Uuid(), nullable=False, comment='상위 공통코드 그룹 ID'),
    sa.Column('code_key', sa.String(length=100), nullable=False, comment='코드 키 (예: RETAIL, LOAN)'),
    sa.Column('code_value', sa.String(length=200), nullable=False, comment='코드 값/표시명 (예: 리테일, 대출)'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='정렬 순서'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='활성화 여부'),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False, comment='추가 속성/메타데이터 (선택사항)'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['common_code_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'code_key', name='uq_common_code_item_group_key')
    )
    op.create_index(op.f('ix_common_code_items_group_id'), 'common_code_items', ['group_id'], unique=False)
    op.create_index(op.f('ix_common_code_items_is_active'), 'common_code_items', ['is_active'], unique=False)
    op.drop_index(op.f('idx_consultation_vectors_branch'), table_name='consultation_vectors')
    op.drop_index(op.f('idx_consultation_vectors_business'), table_name='consultation_vectors')
    op.drop_index(op.f('idx_consultation_vectors_error'), table_name='consultation_vectors')
    op.drop_table('consultation_vectors')
    op.drop_index(op.f('idx_manual_vectors_branch'), table_name='manual_vectors')
    op.drop_index(op.f('idx_manual_vectors_business'), table_name='manual_vectors')
    op.drop_index(op.f('idx_manual_vectors_error'), table_name='manual_vectors')
    op.drop_table('manual_vectors')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manual_vectors',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('branch_code', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('business_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('error_code', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('manual_vectors_pkey'))
    )
    op.create_index(op.f('idx_manual_vectors_error'), 'manual_vectors', ['error_code'], unique=False)
    op.create_index(op.f('idx_manual_vectors_business'), 'manual_vectors', ['business_type'], unique=False)
    op.create_index(op.f('idx_manual_vectors_branch'), 'manual_vectors', ['branch_code'], unique=False)
    op.create_table('consultation_vectors',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('branch_code', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('business_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('error_code', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('consultation_vectors_pkey'))
    )
    op.create_index(op.f('idx_consultation_vectors_error'), 'consultation_vectors', ['error_code'], unique=False)
    op.create_index(op.f('idx_consultation_vectors_business'), 'consultation_vectors', ['business_type'], unique=False)
    op.create_index(op.f('idx_consultation_vectors_branch'), 'consultation_vectors', ['branch_code'], unique=False)
    op.drop_index(op.f('ix_common_code_items_is_active'), table_name='common_code_items')
    op.drop_index(op.f('ix_common_code_items_group_id'), table_name='common_code_items')
    op.drop_table('common_code_items')
    op.drop_index(op.f('ix_common_code_groups_is_active'), table_name='common_code_groups')
    op.drop_index(op.f('ix_common_code_groups_group_code'), table_name='common_code_groups')
    op.drop_table('common_code_groups')
    # ### end Alembic commands ###
