"""Fix common code group_id column type

Revision ID: a11804d6157b
Revises: b9e54cc56a05
Create Date: 2025-12-09 15:12:46.933088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a11804d6157b'
down_revision: Union[str, Sequence[str], None] = 'b9e54cc56a05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_manual_vectors_branch'), table_name='manual_vectors')
    op.drop_index(op.f('idx_manual_vectors_business'), table_name='manual_vectors')
    op.drop_index(op.f('idx_manual_vectors_error'), table_name='manual_vectors')
    op.drop_table('manual_vectors')
    op.drop_index(op.f('idx_consultation_vectors_branch'), table_name='consultation_vectors')
    op.drop_index(op.f('idx_consultation_vectors_business'), table_name='consultation_vectors')
    op.drop_index(op.f('idx_consultation_vectors_error'), table_name='consultation_vectors')
    op.drop_table('consultation_vectors')

    # Drop foreign key constraint first
    op.drop_constraint('common_code_items_group_id_fkey', 'common_code_items', type_='foreignkey')

    # Change column type from UUID to VARCHAR(36)
    op.alter_column('common_code_items', 'group_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_comment='상위 공통코드 그룹 ID',
               existing_nullable=False)

    # Note: Foreign key constraint is not recreated because group_id is now VARCHAR
    # The constraint will be managed at the application level
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert column type from VARCHAR(36) to UUID
    op.alter_column('common_code_items', 'group_id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_comment='상위 공통코드 그룹 ID',
               existing_nullable=False)

    # Recreate foreign key constraint for UUID type
    op.create_foreign_key('common_code_items_group_id_fkey', 'common_code_items',
                         'common_code_groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.create_table('consultation_vectors',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('branch_code', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('business_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('error_code', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('consultation_vectors_pkey'))
    )
    op.create_index(op.f('idx_consultation_vectors_error'), 'consultation_vectors', ['error_code'], unique=False)
    op.create_index(op.f('idx_consultation_vectors_business'), 'consultation_vectors', ['business_type'], unique=False)
    op.create_index(op.f('idx_consultation_vectors_branch'), 'consultation_vectors', ['branch_code'], unique=False)
    op.create_table('manual_vectors',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('branch_code', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('business_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('error_code', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('manual_vectors_pkey'))
    )
    op.create_index(op.f('idx_manual_vectors_error'), 'manual_vectors', ['error_code'], unique=False)
    op.create_index(op.f('idx_manual_vectors_business'), 'manual_vectors', ['business_type'], unique=False)
    op.create_index(op.f('idx_manual_vectors_branch'), 'manual_vectors', ['branch_code'], unique=False)
    # ### end Alembic commands ###
