"""Update user model fields: add employee_id, name, department and remove email, display_name

Revision ID: 8851865e5633
Revises: 943361c7c44d
Create Date: 2025-12-05 16:40:37.052192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8851865e5633'
down_revision: Union[str, Sequence[str], None] = '943361c7c44d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # First, drop the old columns
    op.drop_column('users', 'email')
    op.drop_column('users', 'display_name')

    # Add new columns as nullable first
    op.add_column('users', sa.Column('employee_id', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('department', sa.String(length=100), nullable=True))

    # Update existing rows with default values
    op.execute("UPDATE users SET employee_id = 'EMP_' || id WHERE employee_id IS NULL")
    op.execute("UPDATE users SET name = username WHERE name IS NULL")
    op.execute("UPDATE users SET department = 'General' WHERE department IS NULL")

    # Now alter columns to NOT NULL
    op.alter_column('users', 'employee_id', nullable=False)
    op.alter_column('users', 'name', nullable=False)
    op.alter_column('users', 'department', nullable=False)

    # Create unique constraint
    op.create_unique_constraint(None, 'users', ['employee_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('display_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'department')
    op.drop_column('users', 'name')
    op.drop_column('users', 'employee_id')
    # ### end Alembic commands ###
